[tool.poetry]
name = "snmp-json"
version = "0.2.1"
description = "SNMP poller to JSON output"
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pysnmp-lextudio = "^6.2.0"
pydantic = "^2.8.2"
click = "^8.1.7"
pydantic-settings = "^2.3.4"
loguru = "^0.7.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.5.1"
pytest = "^8.2.2"
mypy = "^1.10.1"
codespell = "^2.3.0"
pyflame = "^0.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
"snmp-json" = "snmp_json.__main__:cli"
